### ISSUE TITLE
Feature: User can sign up for app

### ISSUE THREAD

**Issue by ChorongShin** [ChorongShin/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign up for app to sign in with his/her verified email and password.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After user signs up with his/her email and password on the sign-up form page, he/she will be directed to the sign-in form page.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Mobile:
![Screen Shot 2022-07-25 at 5 20 12 PM](https://user-images.githubusercontent.com/91721272/180896515-43661884-804d-45bc-8749-f2b1c6e4fbbb.png)
![Screen Shot 2022-07-25 at 5 20 32 PM](https://user-images.githubusercontent.com/91721272/180896474-811e03dd-99fb-4fcc-bd4e-df7f1765ad42.png)

Desktop:
![Screen Shot 2022-07-25 at 5 25 21 PM](https://user-images.githubusercontent.com/91721272/180896912-96969257-3bfc-48f4-9bb7-f5533644159b.png)
![Screen Shot 2022-07-25 at 5 26 13 PM](https://user-images.githubusercontent.com/91721272/180897043-ef71c8ab-88ff-4aa2-884e-e7bd2c5d003a.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to users table
- [x] Update `data.sql` - insert into "users" table with userId, hashedPasswod, email and createdAt.

### ☁️ Server Tasks

- [x] Update `server/index.js` - create app.post('/api/auth/sign-up) to sign up user with info
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create an AuthPage Component
- [ ] Create a Navbar Component
- [x] Create a AuthForm Component
- [x] Update App Component with renderPage()
- [x] Create a NotFound Component, if necessary

### 🧑‍⚕️ Clean Up Tasks
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
