### ISSUE TITLE
Feature: User can create a baby's profile

### ISSUE THREAD

**Issue by ChorongShin** [ChorongShin/final-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create a baby's profile

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

If user is a first-time user or wants to have another baby's profile,  he/she can input the baby's name, gender, birth date, height, and weight to create a baby's profile.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Mobile:
![Screen Shot 2022-07-25 at 5 37 58 PM](https://user-images.githubusercontent.com/91721272/180898018-746ca075-1916-400d-8e73-371e9092f585.png)

![Screen Shot 2022-07-25 at 5 38 03 PM](https://user-images.githubusercontent.com/91721272/180898032-006ceb23-e38d-4861-80f9-6b43ef386f09.png)

Desktop:
![Screen Shot 2022-07-25 at 5 39 41 PM](https://user-images.githubusercontent.com/91721272/180898230-ea38d915-c6be-4aed-af20-96bbdd895cc9.png)

![Screen Shot 2022-07-25 at 5 39 54 PM](https://user-images.githubusercontent.com/91721272/180898242-b65b7b9f-9c80-4b8e-9456-003af9005634.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] Update `schema.sql` to ...
- [ ] Update `data.sql` to ...

### ☁️ Server Tasks

- [ ] Update `server/index.js` to ...
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client Tasks

- [ ] Create a component - profiles
- [ ] Update component to `server/app.js`

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
